### ISSUE TITLE
fix `rpy2` imports for `havic depcheck`

### ISSUE THREAD

**Issue by schultzm** [schultzm/HAVIC#11]
```
Traceback (most recent call last):
  File "/usr/local/Caskroom/miniconda/base/bin/havic", line 8, in <module>
    sys.exit(main())
  File "/usr/local/Caskroom/miniconda/base/lib/python3.7/site-packages/havic/__main__.py", line 154, in main
    from .utils.check_dependency import Dependency
  File "/usr/local/Caskroom/miniconda/base/lib/python3.7/site-packages/havic/utils/check_dependency.py", line 3, in <module>
    from havic.tests import check_r_dependencies
  File "/usr/local/Caskroom/miniconda/base/lib/python3.7/site-packages/havic/tests/check_r_dependencies.py", line 2, in <module>
    from rpy2.rinterface import RRuntimeError
ImportError: cannot import name 'RRuntimeError' from 'rpy2.rinterface' (/usr/local/Caskroom/miniconda/base/lib/python3.7/site-packages/rpy2/rinterface.py)
```

**Comment by schultzm** [comment]
fixed by switching to `RRuntimeWarning` as opposed to `RRuntimeError`.  Perhaps this was a breaking change in `rpy2`.
