### ISSUE TITLE
trim seqs bug

### ISSUE THREAD

**Issue by schultzm** [schultzm/HAVIC#3]
When no trim seqs are specified, the list search breaks:  

```
Traceback (most recent call last):
  File "/home/schultzm/.local/bin/havic", line 10, in <module>
    sys.exit(main())
  File "/home/schultzm/.local/lib/python3.7/site-packages/havic/__main__.py", line 197, in main
    args.iqtree_threads)
  File "/home/schultzm/.local/lib/python3.7/site-packages/havic/utils/pipeline_runner.py", line 71, in __init__
    .replace("(", "").replace(")", "").rstrip()) for i in trim_seqs]
TypeError: 'NoneType' object is not iterable

```

**Comment by schultzm** [comment]
done

**Comment by schultzm** [comment]
fixed.
